"""
StatSaksham AI — Shared Integration Contracts
Pydantic contracts defining canonical identity, canonical competency,
and cross-module communication payloads.
"""
from datetime import datetime
from enum import Enum
from typing import Optional, List, Literal
from pydantic import BaseModel, Field


# ============================================================================
# 1. CANONICAL IDENTITY CONTRACT
# ============================================================================

class CanonicalIdentity(BaseModel):
    """
    Uniform cross-module identity token anchored to P1/Supabase UUID.
    Maintains explicit, verifiable mappings to module-local identifiers.
    """
    canonical_user_id: str = Field(
        ...,
        description="Canonical UUIDv4 string (matches P1 official_id in Supabase/PostgreSQL)"
    )
    p1_user_id: Optional[str] = Field(
        None,
        description="P1 Official UUID string"
    )
    p2_learner_id: Optional[str] = Field(
        None,
        description="P2 iGOT adapter learner ID string (e.g., 'U001')"
    )
    p3_learner_id: Optional[str] = Field(
        None,
        description="P3 learning progress learner ID string (e.g., 'U001')"
    )
    p4_user_id: Optional[str] = Field(
        None,
        description="P4 SQLite user ID string (e.g., 'usr_demo_001')"
    )
    p5_cadre_id: Optional[str] = Field(
        None,
        description="P5 official government cadre ID string (e.g., 'ISS-2024-8921')"
    )
    full_name: Optional[str] = None
    designation: Optional[str] = None
    department: Optional[str] = None
    email: Optional[str] = None
    role: str = "learner"


# ============================================================================
# 2. CANONICAL COMPETENCY CONTRACT
# ============================================================================

class MappingStatus(str, Enum):
    EXACT = "EXACT"
    HIGH_CONFIDENCE = "HIGH_CONFIDENCE"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    UNRESOLVED = "UNRESOLVED"


class CanonicalCompetency(BaseModel):
    """
    Canonical competency representation anchored to P1's 33 MoSPI competencies.
    """
    competency_id: int = Field(..., ge=1, le=33, description="Canonical MoSPI integer ID (1-33)")
    name: str = Field(..., description="Official competency name")
    category: str = Field(..., description="Official MoSPI category")
    p1_id: int = Field(..., description="P1 database competency ID")
    p4_id: Optional[str] = Field(None, description="Mapped P4 SQLite competency ID (e.g., 'comp_sampling')")
    aliases: List[str] = Field(default_factory=list, description="Known synonyms and module aliases")


# ============================================================================
# 3. CROSS-MODULE SHARED PAYLOAD CONTRACTS
# ============================================================================

class CompetencyGapContract(BaseModel):
    """
    Contract for evaluated competency gaps emitted by P1 for P2 consumption.
    """
    canonical_user_id: str
    competency_id: int
    competency_name: str
    category: str
    current_score: float = Field(..., ge=1.0, le=5.0)
    required_score: float = Field(..., ge=1.0, le=5.0)
    gap: float
    priority: Literal["HIGH", "MEDIUM", "LOW"]
    is_critical: bool
    source_module: str = "P1_COMPETENCY"
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class LearningRecommendationContract(BaseModel):
    """
    Contract for course recommendations generated by P2 based on P1 gaps.
    """
    canonical_user_id: str
    competency_id: int
    competency_name: str
    course_id: str
    course_title: str
    provider: str = "iGOT Karmayogi"
    match_percentage: float = Field(..., ge=0.0, le=100.0)
    source_module: str = "P2_IGOT"
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class LearningEvidenceContract(BaseModel):
    """
    Contract logging study activities in P3 RAG documents.
    """
    canonical_user_id: str
    competency_id: Optional[int] = None
    competency_name: Optional[str] = None
    document_id: str
    topic: str
    action: Literal["DOCUMENT_VIEW", "SEMANTIC_SEARCH", "RAG_CHAT_QUERY", "QUIZ_STARTED"]
    source_module: str = "P3_LEARNING"
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class AssessmentResultContract(BaseModel):
    """
    Contract capturing quiz assessment outcomes emitted by P3 for P1 and P4 consumption.
    """
    canonical_user_id: str
    quiz_id: str
    topic: str
    competency_id: Optional[int] = None
    competency_name: Optional[str] = None
    total_questions: int
    score: int
    accuracy_pct: float = Field(..., ge=0.0, le=100.0)
    score_calibrated_1_to_5: float = Field(
        ...,
        ge=1.0,
        le=5.0,
        description="Linear normalization: 1.0 + (accuracy_pct / 100.0) * 4.0"
    )
    passed: bool
    source_module: str = "P3_ASSESSMENT"
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class MasteryUpdateContract(BaseModel):
    """
    Contract for reporting updated competency levels to P4 analytics and gamification.
    """
    canonical_user_id: str
    competency_id: int
    competency_name: str
    previous_score: float
    new_score: float
    delta: float
    xp_awarded: int = 50
    source_module: str = "P1_COMPETENCY"
    timestamp: datetime = Field(default_factory=datetime.utcnow)
